
# For development
services:
  laggen-client-dev:
    build: 
      context: ./frontend
      dockerfile: dev.Dockerfile
    image: laggen-client-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
      - /app/out
    env_file: 
      - ./frontend/.env.local
    command: sh -c 'echo "Testing env vars:" && printenv && npm run dev'
    ports:
      - 3000:3000
    depends_on:
      - imagefunc-backend-dev
  imagefunc-backend-dev:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: imagefunc-backend-dev
    container_name: imagefunc-dev
    expose:
      - 8080:80
    restart: unless-stopped
    stdin_open: true
    tty: true
    

  
