
version: "3"
services:
  backend:
    image: imagefunc
    build:
     context: ./backend
    container_name: imagefunc
    ports:
      - 8080:80
  frontend:
    image: laggen
    build:
      context: ./frontend
    container_name: laggen
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - LAGGEN_SERVER_FUNC="http://imagefunc/api/BarrelToImage"
 

  
