version: "3"
# For development
services:
  laggen-client-dev:
    build: 
      context: ../frontend
      dockerfile: dev.Dockerfile
    image: laggen-client-dev
    volumes:
      - ../frontend:/app
    environment:
      DEBUG: 'true'
    ports:
      - 3000:3000
  imagefunc-backend-dev:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    image: imagefunc-backend-dev
    container_name: imagefunc
    expose:
      - 8080:80

  
