services:
  laggen-client-prod:
    build: 
      context: ../frontend
      dockerfile: prod.Dockerfile
    image: laggen-client-prod
    container_name: laggen
    ports:
      - 3000:3000
    depends_on:
      - imagefunc-backend-prod
    volumes:
      - ../frontend/prisma:/app/prisma
      # prisma db gets saved + for dev
  imagefunc-backend-prod:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    image: imagefunc-backend-prod
    container_name: imagefunc
    expose:
      - 8080:80